# ----------------------------------------------------------------------------------------------------
# Deploy Web App Template
# ----------------------------------------------------------------------------------------------------
parameters:
- name: appName
  default: 'pul-yaml-99999999'

jobs:
- job: DeployJob
  displayName: Deploy
  pool:
    name: default
  steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'PUL-Connection'
        appType: 'webApp'
        WebAppName: $(appName)
        packageForLinux: '$(System.ArtifactsDirectory)/drop/*.zip'