# ----------------------------------------------------------------------------------------------------
# Reusable template to run a Terraform Apply -- either building a plan or using an existing plan
# ----------------------------------------------------------------------------------------------------
# This variable group is needed in Azure DevOps:
#    az login
#    az pipelines variable-group create 
#      --organization=https://dev.azure.com/<yourAzDOOrg>/ 
#      --project='<yourAzDOProject>' 
#      --name TF-Var-Group-1 
#      --variables 
#          subscriptionId='<yourValue>'
#          tenantId='<yourValue>'
#          clientId='<yourValue>'
#          clientSecret='<yourValue>'
#          tfStateResourceGroup='<yourValue>'                   <-- like rg-tfstate-ado
#          tfStateStorageAccount='<globallyUniqueStorageName>'  <-- globally unique name for storage account
# ----------------------------------------------------------------------------------------------------
parameters:
- name: env
  type: string
- name: serviceConnectionName
  type: string
- name: variableSetName
  type: string
- name: pipelineResourceIdentifier # supplied if this is deployed with artifacts from another pipeline
  default: '' # internal identifier for the resource

- name: terraFormPath
  default: '/infra/tf'
  type: string

- name: scriptsFolderName
  default: 'scripts'
  type: string
- name: configFolderName
  default: 'config'
  type: string

- name: backendConfigFileName
  type: string
  default: ''

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: Initialize_Terraform_${{ parameters.env }}
  displayName: InitializeTerraform_${{ parameters.env }}
  environment: ${{ parameters.env }}

- job: Terraform_Apply_${{ parameters.env }}
  displayName: 'Terraform Apply - ${{ parameters.env }}'

  variables:
    - group: TF-Var-Group-1
    - template: ../vars/var-common.yml

    - name: env
      value: ${{ parameters.env }}

    - name: pipelineResourcePath
      value: '$(Pipeline.Workspace)/${{ parameters.pipelineResourceIdentifier }}'
    - name: pipelineResourceDropPath
      value: '$(Pipeline.Workspace)/${{ parameters.pipelineResourceIdentifier }}/tfplan'

    - name: scriptsFolder
      value: '${{ parameters.terraFormPath }}/${{ parameters.scriptsFolderName }}'
    - name: scriptsWorkingDirectory
      value: '$(Build.SourcesDirectory)$(scriptsFolder)'

    - name: configFolder
      value: '${{ parameters.terraFormPath }}/${{ parameters.configFolderName }}'
    - name: configWorkingDirectory
      value: '$(Build.SourcesDirectory)$(configFolder)'

    - name: backendConfigFileFullPath
      value: '$(configWorkingDirectory)/${{ parameters.backendConfigFileName }}' 

    - name: requestorName
      value: '$(Build.RequestedFor)'
    - name: requestorEmail
      value: '$(Build.RequestedForEmail)'

  # ----------------------------------------------------------------------------------------------------
  steps:
  - checkout: self

  # ----------------------------------------------------------------------------------------------------
  # if a Pipeline Resource WAS supplied (previously built elsewhere), then copy it over and show info
  # ----------------------------------------------------------------------------------------------------
  - ${{ if ne(parameters.pipelineResourceIdentifier, '') }}:
    - template: tf-steps-download-artifacts-template.yml
      parameters:
        pipelineResourceIdentifier: ${{ parameters.pipelineResourceIdentifier }}
  # ----------------------------------------------------------------------------------------------------
  # /end - if a Pipeline Resource...
  # ----------------------------------------------------------------------------------------------------

  - template: tf-steps-cli-login-template.yml

  - template: tf-steps-display-info-template.yml

  - ${{ if eq(parameters.variableSetName, 'dynamic') }}:
    - template: tf-steps-replace-variables-template.yml
      parameters:
        backendConfigFileFullPath: $(backendConfigFileFullPath)

  - template: tf-steps-install-init-template.yml

  # ----------------------------------------------------------------------------------------------------
  # if a Pipeline Resource was NOT supplied, then just build the TF Plan inline
  # ----------------------------------------------------------------------------------------------------
  - ${{ if eq(parameters.pipelineResourceIdentifier, '') }}:
    - task: Bash@3
      displayName: Create TF Plan
      env:
        ARM_SUBSCRIPTION_ID: $(subscriptionId)
        ARM_TENANT_ID: $(tenantId)
        ARM_CLIENT_ID: $(clientId)
        ARM_CLIENT_SECRET: $(clientSecret)
      inputs:
        targetType: 'inline'
        workingDirectory: $(scriptsWorkingDirectory)
        script: |
          echo "Executing: terraform plan -var-file=$(configWorkingDirectory)/*.tfvars"
          find $(configWorkingDirectory) -name "*.tfvars" -exec echo   -var-file={} \;
          terraform plan $(find $(configWorkingDirectory) -name "*.tfvars" -exec echo -var-file={} \;) -out tfplan

  - task: CmdLine@2
    displayName: Display Plan Contents
    continueOnError: true
    inputs:
      script: |
        echo "##[group]Contents of File tfplan"
        cat $(scriptsWorkingDirectory)/tfplan
        echo "##[endgroup]"

  # ----------------------------------------------------------------------------------------------------
  # if a Pipeline Resource WAS supplied (previously built elsewhere), then display the plan they created
  # ----------------------------------------------------------------------------------------------------
  - ${{ if ne(parameters.pipelineResourceIdentifier, '') }}:
    - task: Bash@3
      displayName: Show TF Plan
      continueOnError: true  # we don't need this once everything is working...!  just enabled for debugging/testing!
      env:
        ARM_SUBSCRIPTION_ID: $(subscriptionId)
        ARM_TENANT_ID: $(tenantId)
        ARM_CLIENT_ID: $(clientId)
        ARM_CLIENT_SECRET: $(clientSecret)
      inputs:
        targetType: 'inline'
        workingDirectory: $(scriptsWorkingDirectory)
        script: |
          echo "Executing: terraform show tfplan"
          terraform show tfplan

  - task: Bash@3
    displayName: Apply TF Plan
    env:
      ARM_SUBSCRIPTION_ID: $(subscriptionId)
      ARM_TENANT_ID: $(tenantId)
      ARM_CLIENT_ID: $(clientId)
      ARM_CLIENT_SECRET: $(clientSecret)
    inputs:
      targetType: 'inline'
      workingDirectory: $(scriptsWorkingDirectory)
      script: |
        echo "Executing: terraform apply tfplan"
        terraform apply tfplan
